POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVrYWkiLCJpZCI6IjYwNmI4ZTIzMzlhOWViMmQ4Y2VjNWMwMCIsImlhdCI6MTYzMTgyOTQ2N30.YB85tTdE63z2iIzQdElP7DFVsdJMWSHXjBmz35766w8

{
   "likes": 2,
   "title": "Type wars",
   "author": "Robert C. Martin",
   "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html"
}