DELETE http://localhost:3003/api/blogs/60ecb883353b270d94b23d1d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QtYSIsImlkIjoiNjEwYzcxNjI0ODJjN2MzZjY4ZTQ2N2NlIiwiaWF0IjoxNjMwODgzNTQ0fQ.N7gecmyaLhz0BxS8fCgMfepTBGreTaA7aV5j5BsOiwU